manifest = "9720e49e12d8ea108c6d547310486c6119e5a59788495d6ca58d48199f2d3cbb"

[[dependency]]
package = "github.com/buckaroo-pm/oatpp"
target = "//:oatpp"

[[dependency]]
package = "github.com/buckaroo-pm/pkg-config-curl"
target = "//:curl"

[lock."github.com/buckaroo-pm/oatpp"]
versions = [ "branch=master" ]
revision = "148e47df363ebea5b8d99476d0741a47ccf75623"

[lock."github.com/buckaroo-pm/oatpp".lock."github.com/buckaroo-pm/host-pthread"]
versions = [ "branch=master" ]
revision = "a62519aa69c8e3243d6065fbf4c1d2de072f86f6"

[lock."github.com/buckaroo-pm/pkg-config-curl"]
versions = [ "branch=master" ]
revision = "c0eac677dc0066d1c994bf68edd314deebe7cb74"
