manifest = "4b3b561e2fb4ff1c8c2cccaa647838e9f4d3bfca1b8709a998af18f37523ebb8"

[[dependency]]
package = "github.com/buckaroo-pm/oatpp"
target = "//:oatpp"

[[dependency]]
package = "github.com/buckaroo-pm/pkg-config-curl"
target = "//:curl"

[lock."github.com/buckaroo-pm/oatpp"]
version = "branch=master"
revision = "148e47df363ebea5b8d99476d0741a47ccf75623"

[lock."github.com/buckaroo-pm/oatpp".lock."github.com/buckaroo-pm/host-pthread"]
version = "branch=master"
revision = "a62519aa69c8e3243d6065fbf4c1d2de072f86f6"

[lock."github.com/buckaroo-pm/pkg-config-curl"]
version = "branch=master"
revision = "c0eac677dc0066d1c994bf68edd314deebe7cb74"
